//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGRemotePDFPageProxy_h
#define CGRemotePDFPageProxy_h
@import Foundation;

#include "CGRemotePDFPageProtocol-Protocol.h"

@interface CGRemotePDFPageProxy : NSObject {
    /* instance variables */
    id<CGRemotePDFPageProtocol, NSXPCProxyCreating> _pageProxy;
}

@property(readonly) NSUUID *identifier;
@property(readonly) long long rotation;
@property(readonly) NSString *pageText;

/* instance methods */
- (void)drawWithBox:(int)box size:(struct CGSize {
    double x0;
    double x1;
})size colorSpace:(id)space options:(id)options completion:(id /* block */)completion;
- (id)initWithRemotePage:(id)page;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})rectForBox:(int)box;

@end

#endif /* CGRemotePDFPageProxy_h */
