//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGRemotePDFDocumentProxy_h
#define CGRemotePDFDocumentProxy_h
@import Foundation;

#include "CGRemotePDFDocumentProtocol-Protocol.h"

@interface CGRemotePDFDocumentProxy : NSObject {
    /* instance variables */
    id<CGRemotePDFDocumentProtocol, NSXPCProxyCreating> _documentProxy;
}

@property(readonly) NSDictionary *infoDictionary;
@property(readonly) _Bool unlocked;
@property(readonly) _Bool encrypted;
@property(readonly) unsigned long long pageCount;

/* instance methods */
- (void)getPageAtIndex:(long long)index completion:(id /* block */)completion;
- (void)getVersionMajor:(long long *)major andMinor:(long long *)minor;
- (id)initWithRemoteDocument:(id)document;
- (_Bool)isEncrypted;
- (_Bool)isUnlocked;
- (id)pageProxyForRemotePage:(id)page;
- (id)sync_pageAtIndex:(long long)index;

@end

#endif /* CGRemotePDFDocumentProxy_h */
