//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGRemotePDFDocumentProtocol_Protocol_h
#define CGRemotePDFDocumentProtocol_Protocol_h
@import Foundation;

@protocol CGRemotePDFDocumentProtocol <NSObject>

@required

/* required instance methods */
- (void)getIsEncrypted:(id /* block */)encrypted;
- (void)getInfo:(id /* block */)info;
- (void)getIsUnlocked:(id /* block */)unlocked;
- (void)getPageAtIndex:(long long)index completion:(id /* block */)completion;
- (void)getPageCount:(id /* block */)count;
- (void)getVersion:(id /* block */)version;

@optional

@end

#endif /* CGRemotePDFDocumentProtocol_Protocol_h */
