//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGRemotePDFServiceProxy_h
#define CGRemotePDFServiceProxy_h
@import Foundation;

#include "CGRemotePDFServiceProtocol-Protocol.h"

@interface CGRemotePDFServiceProxy : NSObject {
    /* instance variables */
    NSXPCConnection *_connection;
    id<CGRemotePDFServiceProtocol, NSXPCProxyCreating> _proxy;
}

/* class methods */
+ (id)sharedInstance;
+ (id)interface;

/* instance methods */
- (void)dealloc;
- (id)initWithError:(id *)error;
- (void)newRemotePDFDocumentProxyWithData:(id)data withReply:(id /* block */)reply;
- (void)newRemotePDFDocumentWithData:(id)data completion:(id /* block */)completion;

@end

#endif /* CGRemotePDFServiceProxy_h */
