//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGRemotePDFPageProtocol_Protocol_h
#define CGRemotePDFPageProtocol_Protocol_h
@import Foundation;

@protocol CGRemotePDFPageProtocol <NSObject>

@required

/* required instance methods */
- (void)drawWithBox:(int)box size:(struct CGSize {
    double x0;
    double x1;
})size colorSpace:(id)space options:(id)options completion:(id /* block */)completion;
- (void)getBoxRect:(int)rect completion:(id /* block */)completion;
- (void)getIdentifier:(id /* block */)identifier;
- (void)getPageText:(id /* block */)text;
- (void)getRotation:(id /* block */)rotation;

@optional

@end

#endif /* CGRemotePDFPageProtocol_Protocol_h */
