//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGVirtualDisplayDescriptor_h
#define CGVirtualDisplayDescriptor_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface CGVirtualDisplayDescriptor : NSObject

@property(readonly, nonatomic) NSDictionary *displayInfo;
@property(nonatomic) unsigned int vendorID;
@property(nonatomic) unsigned int productID;
@property(nonatomic) unsigned int serialNumber;
@property(retain, nonatomic) NSString *name;
@property(nonatomic) struct CGSize {
    double x0;
    double x1;
} sizeInMillimeters;
@property(nonatomic) unsigned int maxPixelsWide;
@property(nonatomic) unsigned int maxPixelsHigh;
@property(nonatomic) struct CGPoint {
    double x0;
    double x1;
} redPrimary;
@property(nonatomic) struct CGPoint {
    double x0;
    double x1;
} greenPrimary;
@property(nonatomic) struct CGPoint {
    double x0;
    double x1;
} bluePrimary;
@property(nonatomic) struct CGPoint {
    double x0;
    double x1;
} whitePoint;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(copy, nonatomic) id /* block */ terminationHandler;
@property(nonatomic) unsigned int serialNum;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)dispatchQueue;
- (void)setDispatchQueue:(id)queue;
- (void)setDisplayInfoValue:(id)value forKey:(id)key;

@end

#endif /* CGVirtualDisplayDescriptor_h */
