//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGVirtualDisplay_h
#define CGVirtualDisplay_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface CGVirtualDisplay : NSObject {
    /* instance variables */
    void *_client;
    double _refreshDeadline;
    _Bool _isReference;
    unsigned int _serverRPC_port;
    unsigned int _proxyRPC_port;
    unsigned int _clientHandler_port;
}

@property(readonly, nonatomic) unsigned int vendorID;
@property(readonly, nonatomic) unsigned int productID;
@property(readonly, nonatomic) unsigned int serialNumber;
@property(readonly, nonatomic) unsigned int serialNum;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) struct CGSize {
    double x0;
    double x1;
} sizeInMillimeters;
@property(readonly, nonatomic) unsigned int maxPixelsWide;
@property(readonly, nonatomic) unsigned int maxPixelsHigh;
@property(readonly, nonatomic) struct CGPoint {
    double x0;
    double x1;
} redPrimary;
@property(readonly, nonatomic) struct CGPoint {
    double x0;
    double x1;
} greenPrimary;
@property(readonly, nonatomic) struct CGPoint {
    double x0;
    double x1;
} bluePrimary;
@property(readonly, nonatomic) struct CGPoint {
    double x0;
    double x1;
} whitePoint;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(readonly, copy, nonatomic) id /* block */ terminationHandler;
@property(readonly, nonatomic) unsigned int displayID;
@property(readonly, nonatomic) unsigned int hiDPI;
@property(readonly, nonatomic) unsigned int rotation;
@property(readonly, nonatomic) NSArray *modes;

/* instance methods */
- (void)dealloc;
- (_Bool)applySettings:(id)settings;
- (id)initWithDescriptor:(id)descriptor;

@end

#endif /* CGVirtualDisplay_h */
