//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CGVirtualDisplayMode_h
#define CGVirtualDisplayMode_h
@import Foundation;

@interface CGVirtualDisplayMode : NSObject {
    /* instance variables */
    unsigned int _transferFunction;
}

@property(readonly, nonatomic) unsigned int width;
@property(readonly, nonatomic) unsigned int height;
@property(readonly, nonatomic) double refreshRate;

/* instance methods */
- (id)initWithWidth:(unsigned int)width height:(unsigned int)height refreshRate:(double)rate;
- (id)initWithWidth:(unsigned int)width
              height:(unsigned int)height
         refreshRate:(double)rate
    transferFunction:(unsigned int)function;
- (void)setTransferFunction:(unsigned int)function;
- (unsigned int)transferFunction;

@end

#endif /* CGVirtualDisplayMode_h */
