//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPAnnotation_h
#define CPAnnotation_h
@import Foundation;

#include "CPGraphicObject.h"

@interface CPAnnotation : CPGraphicObject

@property struct CGPDFAnnotation *cgAnnotation;

/* instance methods */
- (void)dealloc;
- (id)initWithCGPDFAnnotation:(struct CGPDFAnnotation *)cgpdfannotation;

@end

#endif /* CPAnnotation_h */
