//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPColumnMaker_h
#define CPColumnMaker_h
@import Foundation;

#include "CPZone.h"

@interface CPColumnMaker : NSObject {
    /* instance variables */
    NSMutableArray *columns;
    CPZone *currentZone;
    NSMutableArray *allParagraphs;
    NSMutableArray *thinHorizontalShapes;
    NSMutableArray *otherShapes;
    NSMutableArray *images;
    NSMutableArray *paragraphWrappers;
    double maxParagraphDistance;
}

@property struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
} pageBounds;

/* instance methods */
- (void)dealloc;
- (id)init;
- (double)averageSpacing:(id)spacing;
- (id)columns;
- (void)anchorImages;
- (void)callOuts;
- (_Bool)canSafelyAdd:(id)add to:(id)to;
- (id)chunkAbove:(id)above in:(id)in;
- (_Bool)closeImagesBetween:(id)between and:(id)and bounds:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;
- (_Bool)column:(id)column isLinkedBelowTo:(id)to;
- (_Bool)cuttingShapeBetween:(id)between and:(id)and;
- (void)intersectionCallout:(id)callout;
- (_Bool)intervalOverlapLeft:(double)left right:(double)right paragraphs:(id)paragraphs;
- (void)makeColumnsFrom:(id)from zone:(id)zone;
- (_Bool)paragraph:(id)paragraph isAbove:(id)above;
- (_Bool)paragraph:(id)paragraph isBelow:(id)below;
- (_Bool)paragraph:(id)paragraph isLinkedBelowTo:(id)to;
- (_Bool)paragraph:(id)paragraph notOnSameShapeAs:(id)as;
- (id)paragraphAbove:(id)above in:(id)in;
- (id)paragraphBelow:(id)below in:(id)in;
- (void)partitionShapes:(id)shapes;
- (void)splitColumns:(id)columns;

@end

#endif /* CPColumnMaker_h */
