//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPCompoundGraphic_h
#define CPCompoundGraphic_h
@import Foundation;

#include "CPGraphicObject.h"

@interface CPCompoundGraphic : CPGraphicObject

/* instance methods */
- (void)accept:(id)accept;
- (id)initWithGraphicObjects:(id)objects withRenderedBounds:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;

@end

#endif /* CPCompoundGraphic_h */
