//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPCompoundGraphicMaker_h
#define CPCompoundGraphicMaker_h
@import Foundation;

#include "CPChunk.h"
#include "CPCluster.h"
#include "CPDisposable-Protocol.h"

@interface CPCompoundGraphicMaker : NSObject <CPDisposable> {
    /* instance variables */
    CPChunk *parentChunk;
    _Bool shapesAreVectorGraphics;
    unsigned int shapeCount;
    id *shapes;
    double pageSpread;
    CPCluster *cluster;
    unsigned int groupInfoCount;
    struct {
        unsigned int x0;
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x1;
    } *groupInfoArray;
    _Bool disposed;
}

/* class methods */
+ (_Bool)makeCompoundGraphicsInZonesOf:(id)of;

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (void)addGroupInfoWithIndex:(unsigned int)index bounds:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;
- (void)coalesceShapeGroups;
- (_Bool)findClusterLevel;
- (_Bool)groupOverlappingGraphics;
- (id)initWithGraphicsIn:(id)in ofClass:(Class)class;
- (void)makeCompoundGraphicFromShapesAtIndex:(unsigned int)index count:(unsigned int)count;
- (_Bool)makeCompoundGraphics;
- (_Bool)makeCompoundGraphicsFromShapeGroups;

@end

#endif /* CPCompoundGraphicMaker_h */
