//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPColumn_h
#define CPColumn_h
@import Foundation;

#include "CPRotatedRegion.h"

@interface CPColumn : CPRotatedRegion {
    /* instance variables */
    _Bool hasCentredParagraph;
    _Bool hasColumnBreak;
    double maxLeftPad;
    double maxRightPad;
    double maxRight;
    double minLeft;
}

@property _Bool complete;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)init;
- (void)accept:(id)accept;
- (double)leftPad;
- (double)selectionBottom;
- (void)setMaxRightPad:(double)pad;
- (int)inOrder;
- (double)bottomBaseline;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})columnBounds;
- (_Bool)hasCentredParagraph;
- (_Bool)isBoxRegion;
- (_Bool)isGraphicalRegion;
- (_Bool)isImageRegion;
- (_Bool)isRowRegion;
- (_Bool)isShapeRegion;
- (double)maxLeftPad;
- (double)maxRightPad;
- (int)outOrder;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})paddedBounds;
- (double)rightPad;
- (void)setHasCentredParagraph:(_Bool)paragraph;
- (void)setHasColumnBreak:(_Bool)break;
- (void)setIsImageRegion:(_Bool)region;
- (void)setMaxLeftPad:(double)pad;

@end

#endif /* CPColumn_h */
