//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPFontInfo_h
#define CPFontInfo_h
@import Foundation;

#include "CPDisposable-Protocol.h"

@interface CPFontInfo : NSObject <CPDisposable> {
    /* instance variables */
    struct __CFData *fontData;
    const char *dataPtr;
    unsigned int offset;
    unsigned int fontDataLength;
    _Bool valid;
}

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (_Bool)getDescriptor:(struct {
    double x0;
    double x1;
    unsigned int x2;
    struct CGRect {
        struct CGPoint {
            double x0;
            double x1;
        } x0;
        struct CGSize {
            double x0;
            double x1;
        } x1;
    } x3;
    double x4;
    double x5;
    double x6;
    double x7;
    double x8;
    double x9;
    double x10;
    double x11;
    double x12;
    double x13;
    double x14;
    double x15;
    double x16;
    double x17;
} *)descriptor;
- (id)initWithFontData:(struct __CFData *)data;
- (int)kernUnitsPerEm;
- (struct __CFData *)newKernData;
- (unsigned char)readByte;
- (float)readFloat;
- (int)readLong;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})readRect;
- (unsigned int)readUnsignedLong;

@end

#endif /* CPFontInfo_h */
