//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPGenericVisitor_h
#define CPGenericVisitor_h
@import Foundation;

#include "CPVisitor-Protocol.h"

@interface CPGenericVisitor : NSObject <CPVisitor>

/* instance methods */
- (void)visitParagraph:(id)paragraph;
- (void)visitBody:(id)body;
- (void)visitChunk:(id)chunk;
- (void)visitColumn:(id)column;
- (void)visitCompoundGraphic:(id)graphic;
- (void)visitImage:(id)image;
- (void)visitImageRegion:(id)region;
- (void)visitLayoutArea:(id)area;
- (void)visitPage:(id)page;
- (void)visitRegion:(id)region;
- (void)visitShape:(id)shape;
- (void)visitShapeRegion:(id)region;
- (void)visitTextBox:(id)box;
- (void)visitTextLine:(id)line;
- (void)visitZone:(id)zone;

@end

#endif /* CPGenericVisitor_h */
