//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPGraphicObject_h
#define CPGraphicObject_h
@import Foundation;

#include "CPChunk.h"
#include "CPGraphicUser-Protocol.h"
#include "CPParagraph.h"
#include "CPTextLine.h"

@interface CPGraphicObject : CPChunk {
    /* instance variables */
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } renderedBounds;
    _Bool isInZoneBorder;
    int zoneGraphicType;
    CPTextLine *anchoringTextLine;
    CPChunk<CPGraphicUser> *user;
}

@property(nonatomic) unsigned int clipIndex;
@property(retain, nonatomic) CPParagraph *anchoringParagraph;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)user;
- (void)setUser:(id)user;
- (_Bool)isVisible;
- (int)zoneGraphicType;
- (unsigned short)unicode;
- (id)anchoringTextLine;
- (_Bool)canBeContainer;
- (_Bool)isInZoneBorder;
- (_Bool)isIndivisible;
- (_Bool)isNarrow;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})renderedBounds;
- (void)setAnchoringTextLine:(id)line;
- (void)setIsInZoneBorder:(_Bool)border;
- (void)setZoneGraphicType:(int)type;

@end

#endif /* CPGraphicObject_h */
