//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPGuideFinder_h
#define CPGuideFinder_h
@import Foundation;

#include "CPCluster.h"
#include "CPDisposable-Protocol.h"
#include "CPZone.h"

@interface CPGuideFinder : NSObject <CPDisposable> {
    /* instance variables */
    CPZone *contentZone;
    unsigned int countOfWordsInZone;
    double *anchorArray;
    double *rightHandSideArray;
    struct {
        double x0;
        double x1;
        double x2;
        double x3;
        int x4;
        int *x5;
        struct CPPDFStyle *x6;
    } *crossingWordArray;
    CPCluster *anchors;
    CPCluster *rightHandSides;
    double medianFontSizeOfFirstCharacter;
    double medianFontSizeOfLastCharacter;
    NSMutableArray *gutters;
    NSMutableArray *leftGuides;
    NSMutableArray *rightGuides;
}

/* class methods */
+ (_Bool)guideSeparates:(id)separates from:(id)from;
+ (_Bool)gutterSeparates:(id)separates from:(id)from;
+ (void)reclusterBetweenGuides:(id)guides;
+ (void)reclusterPreservingAlignment:(id)alignment;

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (id)gutters;
- (_Bool)addStripTo:(id)to
             bottom:(double)bottom
               left:(double)left
                top:(double)top
              right:(double)right;
- (void)findGuides;
- (void)findGutters;
- (void)findWordEdgeClusters;
- (void)func:(id)func and:(id)and and:(unsigned int)and and:(unsigned int)and;
- (void)getWordEdges;
- (_Bool)hasGutters;
- (_Bool)hasLeftGuides;
- (_Bool)hasRightGuides;
- (id)initWithContentZone:(id)zone;
- (id)leftGuides;
- (void)markTextLines;
- (double)medianFontSizeOfFirstCharacter;
- (double)medianFontSizeOfLastCharacter;
- (id)rightGuides;
- (void)setAlignForWordWithExtent:(struct {
    double x0;
    double x1;
    double x2;
    double x3;
    int x4;
    int *x5;
    struct CPPDFStyle *x6;
} *)extent stripArray:(id)array stripMax:(double)max;
- (void)splitTextLines;
- (void)splitTextLinesAtBorderWords;
- (void)splitTextLinesBetweenBorderWords;
- (void)subdivideGutterFrom:(unsigned int)from to:(unsigned int)to;
- (void)subdivideLeftGuideAt:(unsigned int)at;
- (void)subdivideRightGuideAt:(unsigned int)at;
- (void)subdivideStripInto:(id)into from:(double)from to:(double)to borderedBy:(struct {
    double x0;
    double x1;
    double x2;
    double x3;
    int x4;
    int *x5;
    struct CPPDFStyle *x6;
} *)by ofCount:(unsigned int)count crossedBy:(struct {
    double x0;
    double x1;
    double x2;
    double x3;
    int x4;
    int *x5;
    struct CPPDFStyle *x6; } *)by ofCount:(unsigned int)count;

@end

#endif /* CPGuideFinder_h */
