//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPHighlighter_h
#define CPHighlighter_h
@import Foundation;

#include "CPTextLine.h"
#include "CPZone.h"

@interface CPHighlighter : NSObject {
    /* instance variables */
    CPZone *boundingZone;
    CPTextLine *textLine;
}

@property(readonly, nonatomic) struct CGColor *color;
@property(nonatomic) struct CPPDFStyle {
    struct CGColor *x0;
    struct CGColorSpace *x1;
    struct CGColor *x2;
    struct CGColorSpace *x3;
    double x4;
    double x5;
    unsigned char x6;
    unsigned char x7;
    int x8;
    double x9;
    id x10;
    double x11;
    struct CGPDFObject *x12;
    struct CGPDFObject *x13;
    struct CGColor *x14;
    struct CPPDFStyle *x15;
} *style;
@property(nonatomic) struct CPPDFStyle {
    struct CGColor *x0;
    struct CGColorSpace *x1;
    struct CGColor *x2;
    struct CGColorSpace *x3;
    double x4;
    double x5;
    unsigned char x6;
    unsigned char x7;
    int x8;
    double x9;
    id x10;
    double x11;
    struct CGPDFObject *x12;
    struct CGPDFObject *x13;
    struct CGColor *x14;
    struct CPPDFStyle *x15;
} *highlightedStyle;

/* class methods */
+ (_Bool)reconstructHighlightFor:(id)for;

/* instance methods */
- (void)highlight;
- (id)initWithTextLine:(id)line inZone:(id)zone ofColor:(struct CGColor *)color;

@end

#endif /* CPHighlighter_h */
