//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPListMaker_h
#define CPListMaker_h
@import Foundation;

#include "CPDisposable-Protocol.h"
#include "CPLayoutArea.h"
#include "CPList.h"

@interface CPListMaker : NSObject <CPDisposable> {
    /* instance variables */
    CPLayoutArea *area;
    NSArray *spacers;
    unsigned int textLineCount;
    id *textLines;
    CPList *list;
}

/* class methods */
+ (void)makeListsInChunk:(id)chunk;
+ (void)makeListsInLayoutArea:(id)area;
+ (void)makeListsInPage:(id)page;

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (void)fetchTextLine:(id)line;
- (void)fetchTextLinesInColumn:(id)column;
- (id)initWithLayoutArea:(id)area;
- (_Bool)makeListFrom:(struct CPListInfo {
    unsigned int x0;
    unsigned int x1;
    struct CGRect {
        struct CGPoint {
            double x0;
            double x1;
        } x0;
        struct CGSize {
            double x0;
            double x1;
        } x1;
    } x2;
    struct __CFString *x3;
    int x4;
    unsigned int x5;
    unsigned int x6;
    int x7;
    _Bool x8;
    _Bool x9;
    _Bool x10;
    void *x11;
} *)from;
- (void)makeListItemFrom:(struct CPListInfo {
    unsigned int x0;
    unsigned int x1;
    struct CGRect {
        struct CGPoint {
            double x0;
            double x1;
        } x0;
        struct CGSize {
            double x0;
            double x1;
        } x1;
    } x2;
    struct __CFString *x3;
    int x4;
    unsigned int x5;
    unsigned int x6;
    int x7;
    _Bool x8;
    _Bool x9;
    _Bool x10;
    void *x11;
} *)from stopAt:(unsigned int)at;
- (void)makeLists;
- (void)makeListsInColumn:(id)column;

@end

#endif /* CPListMaker_h */
