//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPObject_h
#define CPObject_h
@import Foundation;

#include "CPCopying-Protocol.h"
#include "CPPage.h"

@class CPDocument;

@interface CPObject : NSObject <NSCopying, CPCopying> {
    /* instance variables */
    CPObject *parent;
    NSMutableArray *children;
    CPDocument *document;
    CPPage *page;
    long long zOrder;
}

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (_Bool)isEqual:(id)equal;
- (void)performSelector:(SEL)selector;
- (unsigned int)count;
- (void)removeObjectAtIndex:(unsigned int)index;
- (int)depth;
- (id)parent;
- (id)previousSibling;
- (void)remove:(id)remove;
- (id)childAtIndex:(unsigned int)index;
- (id)children;
- (id)document;
- (unsigned long long)indexOf:(id)of;
- (id)nextSibling;
- (void)remove;
- (void)add:(id)add;
- (id)page;
- (void)removeAll;
- (void)setDocument:(id)document;
- (void)setPage:(id)page;
- (id)firstChild;
- (void)accept:(id)accept;
- (void)clearCachedInfo;
- (void)promoteChildren;
- (void)recomputeZOrder;
- (void)addChildren:(id)children;
- (unsigned int)countOfFirstDescendantsOfClass:(Class)class;
- (id)newTakeChildren;
- (void)removeLastChild;
- (void)_printWithIndent:(int)indent;
- (void)add:(id)add atIndex:(unsigned int)index;
- (void)addChildrenOf:(id)of;
- (id)ancestorOfClass:(Class)class;
- (id)childrenNotOfClass:(Class)class;
- (id)childrenOfClass:(Class)class;
- (void)childrenOfClass:(Class)class into:(id)into;
- (void)commonMapFuncCall:(SEL)call
                   target:(id)target
          childrenOfClass:(Class)class
                  ofCount:(int)count;
- (id)copyAndSplitChildrenAtIndex:(unsigned int)index;
- (id)copyWithoutChildren;
- (unsigned int)countOfClass:(Class)class;
- (id)descendantsOfClass:(Class)class;
- (id)descendantsOfClass:(Class)class deep:(_Bool)deep;
- (id)descendantsOfClass:(Class)class omitTraversing:(Class)traversing;
- (void)descendantsOfClass:(Class)class to:(id)to;
- (void)disposeDescendants;
- (id)firstDescendantOfClass:(Class)class;
- (id)firstDescendantsOfClass:(Class)class;
- (id)firstSibling;
- (id)initSuper;
- (id)lastChild;
- (id)lastDescendantOfClass:(Class)class;
- (id)lastSibling;
- (void)map:(SEL)map target:(id)target;
- (void)map:(SEL)map target:(id)target childrenOfClass:(Class)class;
- (void)map:(SEL)map target:(id)target childrenOfClass:(Class)class last:(_Bool)last;
- (void)map:(SEL)map target:(id)target last:(_Bool)last;
- (void)mapSafely:(SEL)safely target:(id)target childrenOfClass:(Class)class;
- (id)newTakeChildrenAmong:(id)among;
- (void)print;
- (void)removeFirstChild;
- (void)setParent:(id)parent;
- (void)setZOrder:(long long)zorder;
- (id)shallowDescendantsOfClass:(Class)class;
- (void)updateZOrder:(long long)zorder;
- (long long)zOrder;

@end

#endif /* CPObject_h */
