//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPParagraphListItem_h
#define CPParagraphListItem_h
@import Foundation;

#include "CPDisposable-Protocol.h"
#include "CPList.h"

@interface CPParagraphListItem : NSObject <CPDisposable> {
    /* instance variables */
    struct __CFArray *paragraphs;
}

@property(retain, nonatomic) CPList *list;
@property(nonatomic) int number;

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (id)init;
- (void)dispose;
- (void)addParagraph:(id)paragraph;
- (id)paragraphAtIndex:(unsigned int)index;
- (unsigned int)paragraphCount;

@end

#endif /* CPParagraphListItem_h */
