//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPParagraphFlow_h
#define CPParagraphFlow_h
@import Foundation;

#include "CPParagraph.h"

@interface CPParagraphFlow : NSObject {
    /* instance variables */
    double fTop;
    NSMutableArray *paragraphsAbove;
    NSMutableArray *paragraphsBelow;
    NSMutableArray *paragraphsLeft;
    NSMutableArray *paragraphsRight;
    _Bool adjacentToCallout;
}

@property(retain, nonatomic) CPParagraph *paragraph;
@property(nonatomic) CPParagraph *nextInColumn;
@property double fLeft;
@property double fRight;
@property double fBottom;
@property _Bool placed;
@property int calloutType;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)ignoreCallouts:(unsigned int)callouts;
- (id)paragraphsAbove;
- (id)paragraphsRight;
- (int)inOrder;
- (id)paragraphsBelow;
- (double)area;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})belowBounds;
- (id)belowTwoSides:(unsigned int)sides;
- (double)dAbove;
- (double)dBelow;
- (int)inOrder:(_Bool)order;
- (id)initWithParagraph:(id)paragraph;
- (_Bool)intervalOverlapLeft:(double)left right:(double)right paragraphs:(id)paragraphs;
- (_Bool)intervalOverlapLeft:(double)left right:(double)right rects:(id)rects;
- (_Bool)intervalOverlapTop:(double)top bottom:(double)bottom paragraphs:(id)paragraphs;
- (int)leftOrder;
- (id)nextParagraphInColumn:(id)column;
- (int)outOrder;
- (id)paragraphsLeft;
- (void)removeFromAbove:(id)above;
- (void)removeFromBelow:(id)below;
- (void)replaceAbove:(id)above withOneOf:(id)of;
- (void)replaceBelow:(id)below withOneOf:(id)of;
- (int)rightOrder;
- (void)setParagraphsAboveIn:(id)in;
- (void)setParagraphsBelowIn:(id)in;
- (void)setParagraphsLeftIn:(id)in;
- (void)setParagraphsRightIn:(id)in;
- (id)simpleRule:(unsigned int)rule;
- (long long)topDescending:(id)descending;
- (id)twoSides:(unsigned int)sides;

@end

#endif /* CPParagraphFlow_h */
