//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPParagraphMaker_h
#define CPParagraphMaker_h
@import Foundation;

#include "CPPage.h"
#include "CPZone.h"

@interface CPParagraphMaker : NSObject {
    /* instance variables */
    NSMutableArray *avail;
    NSMutableArray *paragraphs;
    NSMutableArray *compoundedShapesOnPage;
    _Bool spacingSet;
    double currentSpacing;
    CPZone *parent;
    CPPage *page;
}

/* class methods */
+ (_Bool)line:(id)line alignsWith:(id)with;

/* instance methods */
- (void)dealloc;
- (id)paragraphs;
- (void)addCompoundedShapesOn:(id)on to:(id)to;
- (void)addIntersectingParagraph:(id)paragraph;
- (void)addLinesTo:(id)to;
- (unsigned long long)alignmentOf:(id)of and:(id)and;
- (unsigned long long)alignmentOf:(id)of and:(id)and and:(id)and;
- (_Bool)firstWordOf:(id)of fits:(id)fits indent:(double)indent;
- (_Bool)fitsBelow:(id)below
         alignment:(unsigned long long)alignment
           spacing:(double)spacing
              from:(int)from;
- (int)indexOfUniqueLineBelow:(id)below from:(int)from;
- (_Bool)isGraphicBetween:(id)between and:(id)and;
- (_Bool)line:(id)line isAlignedWith:(id)with;
- (_Bool)line:(id)line isBelow:(id)below;
- (_Bool)line:(id)line isDirectlyBelow:(id)below;
- (int)linesThatOverlapLineAt:(int)at between:(double)between and:(double)and from:(int)from;
- (void)makeParagraphsIn:(id)in;
- (id)newInitialParagraphIn:(id)in;
- (int)paragraph:(id)paragraph splits:(id)splits;
- (_Bool)spacingOf:(id)of and:(id)and and:(id)and is:(double *)is;
- (_Bool)styleOf:(id)of differsFromStyleOf:(id)of;

@end

#endif /* CPParagraphMaker_h */
