//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPParagraph_h
#define CPParagraph_h
@import Foundation;

#include "CPParagraphListItem.h"
#include "CPRotatedRegion.h"

@interface CPParagraph : CPRotatedRegion {
    /* instance variables */
    _Bool noIndentation;
    _Bool below;
    unsigned long long alignment;
    _Bool hasDropCap;
    id flowProperties;
    double preformatWidth;
}

@property(retain, nonatomic) CPParagraphListItem *listItem;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (void)setAlignment:(unsigned long long)alignment;
- (unsigned long long)alignment;
- (unsigned long long)index;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;
- (void)accept:(id)accept;
- (void)explode;
- (double)selectionBottom;
- (_Bool)below;
- (id)flowProperties;
- (_Bool)hasDropCap;
- (_Bool)isBoxRegion;
- (_Bool)isGraphicalRegion;
- (_Bool)isImageRegion;
- (_Bool)isListItemRegion;
- (_Bool)isParagraphRegion;
- (_Bool)isPreformattedWithUnitWidth:(double *)width;
- (_Bool)isRowRegion;
- (_Bool)isShapeRegion;
- (_Bool)isTextRegion;
- (_Bool)noIndentation;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})reducedBounds;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})renderedBounds;
- (void)setBelow:(_Bool)below;
- (void)setFlowProperties:(id)properties;
- (void)setHasDropCap:(_Bool)cap;
- (void)setIsImageRegion:(_Bool)region;
- (void)setIsTextRegion:(_Bool)region;
- (void)setNoIndentation:(_Bool)indentation;

@end

#endif /* CPParagraph_h */
