//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPPage_h
#define CPPage_h
@import Foundation;

#include "CPChunk.h"
#include "CPDisposable-Protocol.h"

@interface CPPage : CPChunk <CPDisposable> {
    /* instance variables */
    int pageNumber;
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } pageCropBox;
    _Bool hasZones;
    _Bool hasTextLines;
    _Bool isDirty;
    _Bool isStartOfSection;
    long long maxLayoutZOrder;
    CPChunk *background;
    float complexity;
    int rotation;
    NSMutableArray *shapesOnPage;
    NSMutableArray *imagesOnPage;
    NSMutableArray *graphicsOnPage;
    NSMutableArray *columnsOnPage;
    NSMutableArray *annotationsOnPage;
    struct CPPDFContext {
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x0;
        unsigned int x1;
        struct CPPDFGraphicState *x2;
        struct CPPDFGraphicState *x3;
        struct CGPDFContentStream *x4[250] unsigned int x5;
        struct PrimitiveBuffer {
            void *x0;
            void *x1;
            void *x2;
            unsigned int x3;
            unsigned int x4;
            unsigned int x5;
            unsigned int x6;
            int x7;
        } x6;
        struct PrimitiveBuffer {
            void *x0;
            void *x1;
            void *x2;
            unsigned int x3;
            unsigned int x4;
            unsigned int x5;
            unsigned int x6;
            int x7;
        } x7;
        struct PrimitiveBuffer {
            void *x0;
            void *x1;
            void *x2;
            unsigned int x3;
            unsigned int x4;
            unsigned int x5;
            unsigned int x6;
            int x7;
        } x8;
        struct CPPDFClipBuffer {
            unsigned int x0;
            unsigned int x1;
            unsigned int x2;
            struct CPPDFClipSequence *x3;
        } x9;
        struct __CFDictionary *x10;
        struct __CFDictionary *x11;
        struct __CFDictionary *x12;
        struct CPPDFStyle *x13;
        int *x14;
        unsigned int x15;
        unsigned int x16;
        unsigned int x17;
        int x18;
        struct CGPDFPage *x19;
        struct CPMultiUnicodes *x20;
        long long x21;
        long long x22;
        unsigned int *x23;
        struct CGPath **x24;
        _Bool x25;
        struct CGPDFTaggedContext *x26;
    } *pdfContext;
    _Bool contextOwner;
    struct CGPDFPage *pdfPage;
    NSMutableArray *textLinesOnPage;
    void *_layout;
    id hitTest;
    _Bool reconstructed;
    struct _opaque_pthread_mutex_t {
        long long __sig;
        char x[56] __opaque;
    } mutex;
}

/* class methods */
+ (void)sortByReadingOrder:(id)order;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)finalize;
- (id)init;
- (struct CGPDFLayout *)layout;
- (id)parent;
- (int)rotation;
- (id)children;
- (void)dispose;
- (void)addColumns:(id)columns;
- (void)setRotation:(int)rotation;
- (struct CPPDFContext {
    struct CGRect {
        struct CGPoint {
            double x0;
            double x1;
        } x0;
        struct CGSize {
            double x0;
            double x1;
        } x1;
    } x0;
    unsigned int x1;
    struct CPPDFGraphicState *x2;
    struct CPPDFGraphicState *x3;
    struct CGPDFContentStream *x4[250] unsigned int x5;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x6;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x7;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x8;
    struct CPPDFClipBuffer {
        unsigned int x0;
        unsigned int x1;
        unsigned int x2;
        struct CPPDFClipSequence *x3;
    } x9;
    struct __CFDictionary *x10;
    struct __CFDictionary *x11;
    struct __CFDictionary *x12;
    struct CPPDFStyle *x13;
    int *x14;
    unsigned int x15;
    unsigned int x16;
    unsigned int x17;
    int x18;
    struct CGPDFPage *x19;
    struct CPMultiUnicodes *x20;
    long long x21;
    long long x22;
    unsigned int *x23;
    struct CGPath **x24;
    _Bool x25;
    struct CGPDFTaggedContext *x26;
} *)PDFContext;
- (void)accept:(id)accept;
- (void)addAnnotation:(id)annotation;
- (id)hitTest;
- (struct CGPDFPage *)pdfPage;
- (void)setPageCropBox:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})box;
- (id)textLinesOnPage;
- (void)addImage:(id)image;
- (void)addShape:(id)shape;
- (id)annotationsOnPage;
- (id)background;
- (id)bodyZone;
- (struct CPPDFClipBuffer {
    unsigned int x0;
    unsigned int x1;
    unsigned int x2;
    struct CPPDFClipSequence *x3;
} *)clipBuffer;
- (id)columnsOnPage;
- (float)complexity;
- (id)graphicsOnPage;
- (_Bool)hasTextLines;
- (_Bool)hasZones;
- (id)imagesOnPage;
- (id)initWithPDFPage:(struct CGPDFPage *)pdfpage;
- (_Bool)isStartOfSection;
- (void)layDownObjectsOnPage;
- (void)layDownObjectsOnPageOld;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})pageCropBox;
- (int)pageNumber;
- (_Bool)populatePDFLayout:(struct CGPDFLayout *)pdflayout;
- (void)reconstruct;
- (void)restoreBackGroundObjectToPage;
- (void)setBackground:(id)background;
- (unsigned int)setCellPositionsOf:(id)of from:(unsigned int)from;
- (void)setComplexity:(float)complexity;
- (unsigned int)setGraphicPositions:(id)positions from:(unsigned int)from;
- (void)setHasTextLines:(_Bool)lines;
- (void)setHasZones:(_Bool)zones;
- (void)setIsStartOfSection:(_Bool)section;
- (void)setPDFContext:(struct CPPDFContext {
    struct CGRect {
        struct CGPoint {
            double x0;
            double x1;
        } x0;
        struct CGSize {
            double x0;
            double x1;
        } x1;
    } x0;
    unsigned int x1;
    struct CPPDFGraphicState *x2;
    struct CPPDFGraphicState *x3;
    struct CGPDFContentStream *x4[250] unsigned int x5;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x6;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x7;
    struct PrimitiveBuffer {
        void *x0;
        void *x1;
        void *x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        int x7;
    } x8;
    struct CPPDFClipBuffer {
        unsigned int x0;
        unsigned int x1;
        unsigned int x2;
        struct CPPDFClipSequence *x3;
    } x9;
    struct __CFDictionary *x10;
    struct __CFDictionary *x11;
    struct __CFDictionary *x12;
    struct CPPDFStyle *x13;
    int *x14;
    unsigned int x15;
    unsigned int x16;
    unsigned int x17;
    int x18;
    struct CGPDFPage *x19;
    struct CPMultiUnicodes *x20;
    long long x21;
    long long x22;
    unsigned int *x23;
    struct CGPath **x24;
    _Bool x25;
    struct CGPDFTaggedContext *x26;
} *)pdfcontext;
- (void)setPageNumber:(int)number;
- (unsigned int)setPositionsOf:(id)of from:(unsigned int)from;
- (unsigned int)setReadingOrder:(id)order from:(unsigned int)from;
- (id)shapesOnPage;
- (void)sortByReadingOrder;
- (unsigned int)traverse:(id)traverse ordinal:(unsigned int)ordinal;

@end

#endif /* CPPage_h */
