//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPPreformatter_h
#define CPPreformatter_h
@import Foundation;

@interface CPPreformatter : NSObject

/* class methods */
+ (void)preformatInPage:(id)page;

/* instance methods */
- (void)preformatIn:(id)in;
- (void)preformatInParagraph:(id)paragraph;

@end

#endif /* CPPreformatter_h */
