//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPRotatedRegion_h
#define CPRotatedRegion_h
@import Foundation;

#include "CPRegion.h"

@interface CPRotatedRegion : CPRegion {
    /* instance variables */
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } normalizedBounds;
    _Bool dirtyNormalizedBounds;
}

/* instance methods */
- (id)init;
- (double)left;
- (double)top;
- (double)bottom;
- (double)center;
- (double)right;
- (struct CGPoint {
    double x0;
    double x1;
})anchor;
- (void)fitBoundsToChildren;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})normalizedBounds;
- (void)resizeWith:(id)with;

@end

#endif /* CPRotatedRegion_h */
