//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPShape_h
#define CPShape_h
@import Foundation;

#include "CPDisposable-Protocol.h"
#include "CPGraphicObject.h"

@interface CPShape : CPGraphicObject <CPDisposable> {
    /* instance variables */
    long long mcid;
    unsigned int pdfObjectID;
    struct CGPath *path;
    _Bool isUprightRectangle;
    int windingRule;
    double lineWidth;
    double miterLimit;
    int lineCap;
    int lineJoin;
    struct CGColor *fillColor;
    struct CGColor *strokeColor;
    struct CGPDFObject *fillObject;
    struct CGPDFObject *strokeObject;
    struct CGAffineTransform {
        double a;
        double b;
        double c;
        double d;
        double tx;
        double ty;
    } paintTransform;
    _Bool boundsComputed;
    _Bool renderedBoundsComputed;
}

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)finalize;
- (id)init;
- (id)string;
- (struct CGPath *)path;
- (void)setPath:(struct CGPath *)path;
- (double)lineWidth;
- (void)setLineWidth:(double)width;
- (id)attributes;
- (void)dispose;
- (void)setStrokeColor:(struct CGColor *)color;
- (void)setWindingRule:(int)rule;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;
- (struct CGColor *)fillColor;
- (_Bool)isVisible;
- (double)miterLimit;
- (void)setFillColor:(struct CGColor *)color;
- (void)setLineCap:(int)cap;
- (void)setLineJoin:(int)join;
- (void)setMiterLimit:(double)limit;
- (struct CGColor *)strokeColor;
- (int)windingRule;
- (void)accept:(id)accept;
- (int)lineCap;
- (void)recomputeBounds;
- (void)setPdfObjectID:(unsigned int)id;
- (_Bool)canCombineWith:(id)with;
- (_Bool)hasFill;
- (void)addShape:(id)shape;
- (struct CGPDFObject *)fillObject;
- (_Bool)hasSamePathAs:(id)as;
- (_Bool)hasStroke;
- (id)initWithPDFShape:(struct CPPDFShape {
    struct CPPDFObject {
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x0;
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x1;
        unsigned int x2;
        unsigned int x3;
    } x0;
    unsigned int x1;
    struct CPPDFStyle *x2;
    int x3;
    struct CGPath *x4;
    _Bool x5;
    struct CGAffineTransform {
        double x0;
        double x1;
        double x2;
        double x3;
        double x4;
        double x5;
    } x6;
    struct CGAffineTransform {
        double x0;
        double x1;
        double x2;
        double x3;
        double x4;
        double x5;
    } x7;
    long long x8;
} *)pdfshape;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})innerBounds;
- (_Bool)isStrokeFor:(id)for;
- (_Bool)isUprightRectangle;
- (int)lineJoin;
- (void)makeLineFromVertex:(struct CGPoint {
    double x0;
    double x1;
})vertex toVertex:(struct CGPoint {
    double x0;
    double x1; })vertex;
- (long long)mcid;
- (struct CGAffineTransform {
    double x0;
    double x1;
    double x2;
    double x3;
    double x4;
    double x5;
})paintTransform;
- (unsigned int)pathElementCount;
- (unsigned int)pdfObjectID;
- (void)recomputeRenderedBounds;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})renderedBounds;
- (void)setFillObject:(struct CGPDFObject *)object;
- (void)setPaintTransform:(struct CGAffineTransform {
    double x0;
    double x1;
    double x2;
    double x3;
    double x4;
    double x5;
})transform;
- (void)setStrokeObject:(struct CGPDFObject *)object;
- (struct CGPDFObject *)strokeObject;
- (long long)zOrder;

@end

#endif /* CPShape_h */
