//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPShapeRegion_h
#define CPShapeRegion_h
@import Foundation;

#include "CPGraphicRegion.h"

@interface CPShapeRegion : CPGraphicRegion

/* instance methods */
- (void)accept:(id)accept;
- (_Bool)isShapeRegion;

@end

#endif /* CPShapeRegion_h */
