//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPSpacerFinder_h
#define CPSpacerFinder_h
@import Foundation;

#include "CPDisposable-Protocol.h"
#include "CPZone.h"

@interface CPSpacerFinder : NSObject <CPDisposable> {
    /* instance variables */
    CPZone *contentZone;
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } zoneBounds;
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } textBounds;
    struct {
        unsigned int allocatedSize;
        unsigned int size;
        unsigned int count;
        struct *stats;
        struct **ordered;
    } spacerSequence;
    NSMutableArray *spacers;
    unsigned int segmentationCount;
    struct {
        id x0;
        unsigned int x1;
        struct *x2;
    } *segmentations;
    struct {
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x0;
        unsigned int x1;
        unsigned int x2;
        unsigned int x3;
        unsigned int x4;
        unsigned int x5;
        unsigned int x6;
        unsigned int x7;
        unsigned int x8;
        unsigned int x9;
        unsigned int x10;
        unsigned int x11;
        unsigned int x12;
        unsigned int x13;
        struct {
            double x0;
            double x1;
        } x14;
        struct {
            double x0;
            double x1;
        } x15;
        struct {
            double x0;
            double x1;
        } x16;
        struct {
            double x0;
            double x1;
        } x17;
        double x18;
        double x19;
        _Bool x20;
        _Bool x21;
        _Bool x22;
    } *qualityEntries;
}

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (id)spacers;
- (void)assessQuality;
- (void)determineValidity;
- (void)findSpacers;
- (id)initWithContentZone:(id)zone;
- (void)initializeJunctions;
- (void)initializeSegmentations;
- (void)splitTextLines;

@end

#endif /* CPSpacerFinder_h */
