//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPTableCell_h
#define CPTableCell_h
@import Foundation;

#include "CPChunk.h"
#include "CPDisposable-Protocol.h"

@interface CPTableCell : CPChunk <CPDisposable> {
    /* instance variables */
    struct {
        struct CGRect {
            struct CGPoint {
                double x0;
                double x1;
            } x0;
            struct CGSize {
                double x0;
                double x1;
            } x1;
        } x0;
        struct CGColor *x1;
        unsigned int x2;
        id *x3;
    } *borders;
    struct CGColor *backgroundColor;
    id *backgroundGraphics;
}

@property(readonly, nonatomic) struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
} cellBounds;
@property(nonatomic) struct {
    long long x0;
    long long x1;
} rowSpan;
@property(nonatomic) struct {
    long long x0;
    long long x1;
} columnSpan;
@property(readonly, nonatomic) unsigned int backgroundGraphicCount;

/* instance methods */
- (void)dealloc;
- (void)finalize;
- (void)dispose;
- (struct CGColor *)backgroundColor;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})boundsOfBorder:(int)border;
- (id)initWithBounds:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds;
- (id)backgroundGraphicAtIndex:(unsigned int)index;
- (struct CGColor *)colorOfBorder:(int)border;
- (long long)compareCellOrdinal:(id)ordinal;
- (unsigned int)graphicCountOfBorder:(int)border;
- (id)graphicObjectOfBorder:(int)border atIndex:(unsigned int)index;
- (void)setBackgroundGraphics:(id)graphics;
- (void)setBorder:(int)border bounds:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})bounds graphics:(id)graphics;

@end

#endif /* CPTableCell_h */
