//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPTextObject_h
#define CPTextObject_h
@import Foundation;

#include "CPChunk.h"

@interface CPTextObject : CPChunk {
    /* instance variables */
    struct CGPoint {
        double x;
        double y;
    } anchor;
    _Bool metricInfoCalculated;
    float maxFontSize;
    double maxFontLineHeight;
}

/* instance methods */
- (void)clearCachedInfo;
- (void)calculateMetrics;
- (double)maxFontLineHeight;
- (float)maxFontSize;
- (void)translateObjectYBy:(double)yby;

@end

#endif /* CPTextObject_h */
