//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPTextBoxMaker_h
#define CPTextBoxMaker_h
@import Foundation;

#include "CPBody.h"
#include "CPZone.h"

@interface CPTextBoxMaker : NSObject {
    /* instance variables */
    CPBody *bodyZone;
    CPZone *mainZone;
}

/* class methods */
+ (void)boxLayoutsIn:(id)in;
+ (void)promoteLayoutsIn:(id)in;

/* instance methods */
- (_Bool)layoutIsSliced:(id)sliced;
- (void)rotate:(id)rotate;
- (void)promoteLayoutsInCertainRegions:(id)regions;
- (void)boxLayout:(id)layout;
- (void)boxLayoutsIn:(id)in;
- (void)makeBoxesWith:(id)with parent:(id)parent;
- (void)promoteLayoutsIn:(id)in;
- (void)rotateTextBox:(id)box;

@end

#endif /* CPTextBoxMaker_h */
