//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPZone_h
#define CPZone_h
@import Foundation;

#include "CPCharSequence.h"
#include "CPGraphicUser-Protocol.h"
#include "CPRegion.h"

@class CPZoneProfile;

@interface CPZone : CPRegion <CPGraphicUser> {
    /* instance variables */
    NSMutableArray *zoneBorders;
    struct CGPoint {
        double x0;
        double x1;
    } *outerVertices;
    struct CGPoint {
        double x0;
        double x1;
    } *swollenOuterVertices;
    double area;
    _Bool isStraddleZone;
    CPZoneProfile *zoneProfile;
    NSArray *leftGuides;
    NSArray *rightGuides;
    NSArray *gutters;
    NSArray *spacers;
    CPCharSequence *charactersInZone;
    _Bool hasRotatedCharacters;
    NSMutableArray *textLinesInZone;
    NSArray *graphicsInZone;
    NSMutableArray *backgroundGraphics;
    unsigned int usedGraphicCount;
    double rotationAngle;
}

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (_Bool)isRectangular;
- (unsigned int)wordCount;
- (_Bool)contains:(id)contains;
- (void)accept:(id)accept;
- (id)gutters;
- (void)setZoneBorders:(id)borders;
- (id)textLinesInZone;
- (void)updatedCharSequenceFrom:(unsigned int)from length:(unsigned int)length;
- (void)addContentFrom:(id)from;
- (void)setRightGuides:(id)guides;
- (void)setZoneProfile:(id)profile;
- (id)spacers;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})zoneBoundsFromVertices:(struct CGPoint {
    double x0;
    double x1; } *)vertices ofCount:(unsigned int)count;
- (void)addPDFChar:(void *)pdfchar;
- (double)area;
- (id)backgroundGraphics;
- (long long)borderZOrder;
- (_Bool)bordersWindClockwise;
- (_Bool)canContain:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})contain;
- (id)charactersInZone;
- (long long)compareArea:(id)area;
- (id)graphicsInZone;
- (_Bool)hasBorders;
- (_Bool)hasNeighborShape:(id)shape;
- (_Bool)hasRotatedCharacters;
- (void)incrementUsedGraphicCount;
- (_Bool)isStraddleZone;
- (_Bool)isZone;
- (id)leftGuides;
- (_Bool)mapToWordPairs:(void * /* function */)pairs passing:(void *)passing;
- (_Bool)mapToWordPairsWithIndex:(void * /* function */)index passing:(void *)passing;
- (_Bool)mapToWords:(void * /* function */)words passing:(void *)passing;
- (_Bool)mapToWordsWithIndex:(void * /* function */)index passing:(void *)passing;
- (long long)neighborZOrder;
- (struct CGColor *)newBackgroundColor;
- (struct CGPoint {
    double x0;
    double x1;
} *)outerVertices;
- (_Bool)rectangleBordersAtLeft:(id *)left top:(id *)top right:(id *)right bottom:(id *)bottom;
- (void)removeUnfilledNeighborShapes;
- (id)rightGuides;
- (double)rotationAngle;
- (void)setCharactersInZone:(id)zone;
- (void)setGutters:(id)gutters;
- (void)setIsStraddleZone:(_Bool)zone;
- (void)setLeftGuides:(id)guides;
- (void)setRotationAngle:(double)angle;
- (void)setSpacers:(id)spacers;
- (struct CGPoint {
    double x0;
    double x1;
} *)swollenOuterVertices;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})swollenZoneBounds;
- (unsigned int)usedGraphicCount;
- (unsigned int)vertexCount;
- (id)zoneBorders;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})zoneBounds;
- (id)zoneProfile;

@end

#endif /* CPZone_h */
