//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPZoneBorderIntersection_h
#define CPZoneBorderIntersection_h
@import Foundation;

#include "CPCopying-Protocol.h"
#include "CPZoneBorder.h"

@interface CPZoneBorderIntersection : NSObject <NSCopying, CPCopying> {
    /* instance variables */
    struct CGRect {
        struct CGPoint {
            double x;
            double y;
        } origin;
        struct CGSize {
            double width;
            double height;
        } size;
    } intersectionRect;
    CPZoneBorder *intersectingBorder;
    _Bool forwardVector;
    _Bool backwardVector;
}

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)backwardVector;
- (long long)comparePositionLengthwise:(id)lengthwise;
- (_Bool)forwardVector;
- (id)initSuper;
- (id)intersectingBorder;
- (struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})intersectionRect;
- (void)setBackwardVector:(_Bool)vector;
- (void)setForwardVector:(_Bool)vector;
- (void)setIntersectingBorder:(id)border;
- (void)setIntersectionRect:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})rect;

@end

#endif /* CPZoneBorderIntersection_h */
