//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPZoneBorderNeighbor_h
#define CPZoneBorderNeighbor_h
@import Foundation;

#include "CPCopying-Protocol.h"
#include "CPShape.h"

@interface CPZoneBorderNeighbor : NSObject <NSCopying, CPCopying> {
    /* instance variables */
    CPShape *neighborShape;
    int shapeSide;
}

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initSuper;
- (id)neighborShape;
- (void)setNeighborShape:(id)shape;
- (void)setShapeSide:(int)side;
- (int)shapeSide;

@end

#endif /* CPZoneBorderNeighbor_h */
