//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPZoneMaker_h
#define CPZoneMaker_h
@import Foundation;

#include "CPCharSequence.h"

@interface CPZoneMaker : NSObject {
    /* instance variables */
    CPCharSequence *charactersOnPage;
}

/* instance methods */
- (void)dealloc;
- (void)addObjectsToStraddler:(id)straddler from:(id)from;
- (void)addZonesWithBoundaryIn:(id)in withBorder:(id)border;
- (unsigned int)categorizeGraphicsIn:(id)in;
- (void)cutHorizontalBorders:(id)borders whereObscuredByShape:(id)shape;
- (void)cutVerticalBorders:(id)borders whereObscuredByShape:(id)shape;
- (void)makeZonesIn:(id)in;
- (void)makeZonesWithBoundaryIn:(id)in;
- (void)mergeQualifyingRectanglesIn:(id)in;
- (id)newZoneForStraddlersFrom:(id)from;
- (_Bool)overlap:(id)overlap with:(id)with;
- (void)splitByRotatation:(id)rotatation inPage:(id)page;

@end

#endif /* CPZoneMaker_h */
