//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.480, BuildCommit: c8897fa0f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1774.3.4.0.0
//
#ifndef CPZoneFilter_h
#define CPZoneFilter_h
@import Foundation;

#include "CPPage.h"

@interface CPZoneFilter : NSObject {
    /* instance variables */
    CPPage *page;
    double minArea;
}

/* class methods */
+ (void)filterZonesInPage:(id)page;

/* instance methods */
- (void)filterZonesInZone:(id)zone;
- (void)findBackgroundGraphicsInZone:(id)zone;
- (void)findUsedGraphicsInZone:(id)zone;
- (id)initWithPage:(id)page;

@end

#endif /* CPZoneFilter_h */
